project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "Zhengquan Cheng"
  description: "Cognition, Imaging, Machine Learning"
  navbar:
    background: "#023a75ff"
    foreground: "#ffffffff"
    left:
      - text: Research
        href: publications.qmd
      - text: Teaching
        href: teaching.qmd
      - text: CV
        href: curriculum.qmd
    right:
      - icon: envelope
        href: "mailto:zhengquancheng27@gmail.com"

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    toc: true
    linkcolor: black



